# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 269631fd10aa42dd0c7f23858f7a5007c75252948cb044edcad0bbbfdb918e02719ef78ec8a0b39e729270e2c0964f651e7d0432854003123e8f93c0dd2bbb8c

test:
  secret_key_base: 5d79e3cabefddde264714f7f1e0281eed3f609596ba4d9b6a2b5575308c6641c500f0893a82077cfdc41ed6a7dc8d4a8176ab1682db8c6f5c3af16ce68cf4a79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
